version: '3.8'

services:
  backend:
    image: elekrady/foshaa-backend:latest
    ports:
      - "3000:3000"
    volumes:
      - backend-data:/usr/src/app/data
    depends_on:
      - mongodb

  admin-dashboard:
    image: elekrady/foshaa-admin-dashboard:latest
    ports:
      - "8080:80"

  wordpress:
    image: elekrady/foshaa-wordpress:latest
    ports:
      - "8081:80"
    volumes:
      - wordpress-data:/var/www/html

  mongodb:
    image: elekrady/foshaa-mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: elekrady/foshaa-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - admin-dashboard
      - wordpress

volumes:
  backend-data:
  wordpress-data:
  mongo-data:

